# Generated by Django 5.0.2 on 2024-02-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movie_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='img',
            field=models.ImageField(upload_to='meadia/gallery'),
        ),
    ]
